services:
  api:
    image: ${DOCKERHUB_USERNAME}/docfinal-api:latest
    ports:
      - "8080:8080"
    restart: always

  ui:
    image: ${DOCKERHUB_USERNAME}/docfinal-ui:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api
