name: Build Push and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build API
        uses: docker/build-push-action@v6
        with:
          context: ./exam-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docfinal-api:latest

      - name: Build UI
        uses: docker/build-push-action@v6
        with:
          context: ./exam-ui
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docfinal-ui:latest

      - name: Deploy AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            curl -fsSL https://get.docker.com | sh

            sudo usermod -aG docker ubuntu

            mkdir -p /home/ubuntu/docfinal

            cat > /home/ubuntu/docfinal/docker-compose.yml <<EOF
            services:
              api:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/docfinal-api:latest
                ports:
                  - "8080:8080"

              ui:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/docfinal-ui:latest
                ports:
                  - "80:80"
            EOF

            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            cd /home/ubuntu/docfinal

            sudo docker compose pull

            sudo docker compose up -d
